//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliTransCentre.Models.DBObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountTransaction
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> TransactionTypeId { get; set; }
        public string PayFrom { get; set; }
        public string PayTo { get; set; }
        public Nullable<System.DateTime> TransactionTime { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.Guid> CarId { get; set; }
        public Nullable<System.Guid> CarParkId { get; set; }
        public string Description { get; set; }
        public Nullable<int> DurationInMinutes { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
