//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliTransCentre.Models.DBObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public System.Guid Id { get; set; }
        public string CarNumber { get; set; }
        public string CarType { get; set; }
        public string CarName { get; set; }
        public string Description { get; set; }
        public Nullable<bool> HasBluetooth { get; set; }
        public Nullable<bool> HasWiFi { get; set; }
        public string Revision { get; set; }
    }
}
