//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliTransCentre.Models.DBObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarParkRate
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CarParkId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> FeeRate { get; set; }
        public Nullable<int> RangeLowerBound { get; set; }
        public Nullable<int> RangeUpperBound { get; set; }
    }
}
