//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliTransCentre.Models.DBObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarParkingSpace
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ParkingSpaceId { get; set; }
        public Nullable<System.Guid> CarId { get; set; }
        public Nullable<int> ParkingStatus { get; set; }
        public Nullable<System.Guid> CarParkId { get; set; }
        public Nullable<System.DateTime> EnterTime { get; set; }
        public Nullable<System.DateTime> LeaveTime { get; set; }
    }
}
