//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliTransCentre.Models.DBObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPark
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> FacilityTypeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> CarParkTypeId { get; set; }
        public string StreetNumber { get; set; }
        public string StreetName { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Altitude { get; set; }
        public string ContactName { get; set; }
        public string ContactPhoneNumber { get; set; }
        public Nullable<System.Guid> CarParkRateId { get; set; }
        public Nullable<int> TotalPakingSpace { get; set; }
        public Nullable<int> DisableParkingSpace { get; set; }
        public Nullable<int> LargeParkingSpace { get; set; }
        public Nullable<int> SmallParkingSpace { get; set; }
        public Nullable<bool> IsCharge { get; set; }
        public Nullable<bool> IsManual { get; set; }
        public Nullable<bool> IsPublic { get; set; }
    }
}
