//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliTransCentre.Models.DBObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class carparkmanagement
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> userid { get; set; }
        public Nullable<System.Guid> carparkid { get; set; }
    }
}
