//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliTransCentre.Models.DBObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAccount
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string AccountType { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string CVV { get; set; }
        public string Description { get; set; }
    }
}
