//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliTransCentre.Models.DBObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public System.Guid Id { get; set; }
        public string PasswordHash { get; set; }
        public string Salt { get; set; }
        public string UserId { get; set; }
        public string PIN { get; set; }
        public Nullable<bool> ResetPassword { get; set; }
        public Nullable<System.Guid> PasswordResetCode { get; set; }
        public Nullable<System.Guid> Role { get; set; }
        public string Type { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Salutation { get; set; }
        public string JobTitle { get; set; }
        public string ContactNumber { get; set; }
        public Nullable<bool> LockToIP { get; set; }
        public Nullable<bool> IsTermsAndConditionsAccepted { get; set; }
        public Nullable<System.DateTime> TermsAndConditionsAcceptedDate { get; set; }
        public string Email { get; set; }
        public Nullable<int> LoginFailedCount { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public Nullable<System.Guid> LastUpdatedBy { get; set; }
    }
}
